### ISSUE TITLE
Issue when Genie node is not last node in nodeArray

### ISSUE THREAD

**Issue by bamamat** [mit-ll/LLAMAComm#1]
Using MATLAB 2019a: 
inside CreateShadowLossNodeArray, line 51: nodeArray(1, length(nodes)) = struct('type','','name','','location',''); initializes the array but only sets struct.type to a empty char array for the last element. The other elements of nodeArray are initialized to []. If any nodes besides the last node are genie (case '00' at line 72), then  struct.type = [], which then breaks CreateShadowlossLinkMatrix at line 69: switch nodeArray(colLoop).type because "SWITCH expression must be a scalar or a character vector." My recommended fix would be to set nodeArray(nodeLoop).type = ''; inside case '00' at line 73 of CreateShadowLossNodeArray. 

This may not be an issue in the "supported" MATLAB 2015b, but I thought I would report the issue.

Thanks.

**Comment by gsfawcett-ll** [comment]
Thank you for bringing this problem to my attention. I have resolved the bug by fixing the way nodeArray is allocated, but I also implemented your suggested fix, as I think it makes the code clearer.
